#!/usr/bin/env python3
"""Generate curriculum-parts/lessons-166-278.json (113 lessons)."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "curriculum-parts" / "lessons-166-278.json"

# (lesson, book_id, chapter, verse, NIV 2011 text, historical_context, preceding_narrative, questions)
LESSONS = [
    (166, 41, 16, 15,
     "He said to them, \"Go into all the world and preach the gospel to all creation.\"",
     "<p>Mark's Gospel closes with the risen Jesus commissioning frightened disciples in Galilee. Written for Roman believers facing persecution, Mark emphasizes urgent witness and the cost of following Christ in a empire that demanded Caesar's lordship.</p>",
     "<p>After reports of the empty tomb and appearances, the longer ending of Mark records Jesus rebuking unbelief and hard hearts. He then sends the eleven to proclaim the gospel with signs accompanying those who believe.</p>",
     ["What does preaching the gospel to 'all creation' mean in your context?", "What fears keep you from sharing your faith?", "How does the resurrection empower mission?"]),
    (167, 42, 1, 37,
     "For no word from God will ever fail.",
     "<p>Luke opens his Gospel in the Greco-Roman world with parallel birth stories of John and Jesus. Gabriel's announcement to Mary unfolds against Jewish expectation of Messiah and Roman occupation of Judea.</p>",
     "<p>Mary, a young betrothed woman in Nazareth, learns she will bear God's Son. When she asks how this can be, the angel explains the Holy Spirit's work and points to Elizabeth's miraculous pregnancy as proof.</p>",
     ["When has God's promise seemed impossible in your life?", "How does Mary's faith encourage your obedience?", "What does it mean that God's word never fails?"]),
    (168, 42, 2, 10,
     "But the angel said to them, \"Do not be afraid. I bring you good news that will cause great joy for all the people.\"",
     "<p>Shepherds in Luke represent the marginalized of first-century Palestine — ritually unclean, poor, and overlooked. Caesar Augustus had ordered a census, yet heaven announces a greater King born in Bethlehem.</p>",
     "<p>Angels appear to shepherds keeping night watch over their flocks. Glory fills the sky as they hear that a Savior, Christ the Lord, has been born in David's city.</p>",
     ["Why do you think God announced Jesus' birth to shepherds first?", "What 'good news' do you need to hear today?", "How can joy in Christ reach 'all the people' through you?"]),
    (169, 42, 2, 14,
     "Glory to God in the highest heaven, and on earth peace to those on whom his favor rests.",
     "<p>The heavenly chorus echoes Isaiah's vision of God's glory filling the earth. Roman propaganda promised <em>pax Romana</em>; Luke proclaims peace through a child who fulfills God's covenant with Israel and blesses the nations.</p>",
     "<p>After the angel's announcement of good news, a multitude of the heavenly host praises God. Their song ties divine glory in heaven to peace on earth for those receiving God's gracious favor.</p>",
     ["How is God's peace different from absence of conflict?", "Who around you needs to hear that God's favor rests on them?", "How does worship connect heaven and earth?"]),
    (170, 42, 6, 35,
     "But love your enemies, do good to them, and lend to them without expecting to get anything back. Then your reward will be great, and you will be children of the Most High, because he is kind to the ungrateful and wicked.",
     "<p>Jesus teaches on a level place in Galilee to disciples and crowds shaped by honor-shame culture and Roman taxation. His ethic overturns reciprocal violence and models the Father's indiscriminate kindness.</p>",
     "<p>Luke 6 records the Beatitudes and woes, then commands love for enemies rather than retaliation. Jesus grounds radical generosity in God's own character toward the undeserving.</p>",
     ["Who is hardest for you to love or do good to?", "How does God's kindness toward you shape your treatment of others?", "What does it mean to be children of the Most High?"]),
    (171, 42, 10, 27,
     "He replied, \"'Love the Lord your God with all your heart and with all your soul and with all your strength and with all your mind'; and, 'Love your neighbor as yourself.'\"",
     "<p>A lawyer tests Jesus on the road to Jerusalem. The Shema (Deuteronomy 6) and Leviticus 19 formed the heart of Jewish piety; Jesus unites love for God and neighbor as the law's summary.</p>",
     "<p>When asked what must be done to inherit eternal life, the lawyer cites the law. Jesus affirms his answer and tells the parable of the Good Samaritan to redefine who counts as a neighbor.</p>",
     ["Which part of loving God — heart, soul, strength, or mind — needs growth in you?", "Who is your 'neighbor' that you tend to overlook?", "How do love for God and neighbor connect in daily choices?"]),
    (172, 42, 12, 34,
     "For where your treasure is, there your heart will be also.",
     "<p>Jesus warns a crowd of thousands about hypocrisy and greed while religious leaders oppose him. First-century Palestine knew sharp divides between rich landowners and struggling peasants.</p>",
     "<p>After teaching about storing treasures in heaven rather than on earth, Jesus uses the eye as lamp and warns against serving two masters. He then links treasure and heart inseparably.</p>",
     ["What treasures compete with God for your heart?", "How can you invest in eternal rather than earthly treasure?", "What does your spending reveal about your priorities?"]),
    (173, 42, 15, 7,
     "I tell you that in the same way there will be more rejoicing in heaven over one sinner who repents than over ninety-nine righteous persons who do not need to repent.",
     "<p>Pharisees and scribes grumble that Jesus welcomes sinners. Luke presents Jesus as the seeker of the lost, challenging religious boundaries in table fellowship and pastoral care.</p>",
     "<p>Jesus tells three parables of lost things — a sheep, a coin, and a son. Heaven's joy over one repentant sinner frames the Father's heart for restoration.</p>",
     ["When have you experienced God seeking you while you were 'lost'?", "How can your community celebrate repentance rather than shame?", "Who needs you to pursue them with gospel hope?"]),
    (174, 42, 18, 1,
     "Then Jesus told his disciples a parable to show them that they should always pray and not give up.",
     "<p>Jesus is on his final journey toward Jerusalem, teaching about the kingdom amid opposition. Persistent prayer was a contested practice among Jews and early Christians awaiting God's vindication.</p>",
     "<p>After teaching on the coming of the Son of Man, Jesus introduces the parable of the persistent widow and unjust judge to encourage relentless prayer for justice.</p>",
     ["When have you been tempted to give up praying?", "What does persistent prayer look like in your current situation?", "How does this parable reshape your view of God's timing?"]),
    (175, 42, 19, 10,
     "For the Son of Man came to seek and to save the lost.",
     "<p>Jesus enters Jericho on the way to Passover in Jerusalem. Tax collectors like Zacchaeus were despised collaborators with Rome, yet Jesus stops to bring salvation to a household.</p>",
     "<p>Zacchaeus climbs a sycamore tree to see Jesus. After Jesus invites himself to dinner, Zacchaeus repents and restores what he stole; Jesus declares salvation has come to his house.</p>",
     ["Who do you consider 'lost' or beyond reach?", "How does Jesus' mission redefine your purpose?", "What would it look like for Jesus to seek you today?"]),
    (176, 42, 23, 34,
     "Jesus said, \"Father, forgive them, for they do not know what they are doing.\" And they divided up his clothes by casting lots.",
     "<p>Jesus is crucified outside Jerusalem under Roman authority with Jewish leaders' cooperation. Crucifixion was reserved for slaves and rebels; the scene fulfills Psalm 22 and Isaiah's suffering servant.</p>",
     "<p>After soldiers nail Jesus to the cross and leaders mock him, Jesus prays for his executioners' forgiveness even as they gamble for his garments beneath the sign 'King of the Jews.'</p>",
     ["How does Jesus' prayer on the cross challenge your view of forgiveness?", "Who do you need to forgive who may not understand their wrong?", "What does the cross reveal about God's heart toward enemies?"]),
    (177, 42, 24, 32,
     "They asked each other, \"Were not our hearts burning within us while he talked with us on the road and opened the Scriptures to us?\"",
     "<p>On the day of resurrection, two disciples leave Jerusalem for Emmaus discouraged. Luke shows how risen Jesus interprets Moses and the Prophets to rekindle hope in a shattered community.</p>",
     "<p>Jesus walks unrecognized with Cleopas and another disciple, explaining how Messiah had to suffer. At table he breaks bread, their eyes open, and they rush back to tell the eleven.</p>",
     ["When has Scripture come alive and stirred your heart?", "How does Jesus' presence change disappointment into mission?", "Who needs you to walk alongside them in doubt?"]),
    (178, 43, 1, 12,
     "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God—",
     "<p>John writes to believers facing synagogue expulsion and empire pressure, proclaiming the eternal Word made flesh. First-century adoption language spoke of new identity and inheritance in God's family.</p>",
     "<p>The prologue contrasts those who rejected the light with those receiving Christ. Belief grants not merely status but birth from God rather than merely human descent.</p>",
     ["What does receiving Christ look like beyond a one-time decision?", "How does being God's child reshape your identity?", "What keeps people from receiving the light today?"]),
    (179, 43, 4, 24,
     "God is spirit, and his worshipers must worship in the Spirit and in truth.",
     "<p>Jesus speaks with a Samaritan woman at Jacob's well — crossing ethnic, gender, and religious barriers. Samaritans worshiped on Mount Gerizim while Jews worshiped in Jerusalem; both awaited Messiah.</p>",
     "<p>After exposing her marital history and offering living water, Jesus teaches that true worship is not tied to a mountain but flows from God's nature as Spirit and from truthful encounter with him.</p>",
     ["What false ideas about worship might you need to release?", "How can you worship in Spirit and truth this week?", "What barriers did Jesus cross that you are called to cross?"]),
    (180, 43, 6, 35,
     "Then Jesus declared, \"I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.\"",
     "<p>After feeding five thousand, Jesus teaches in Capernaum's synagogue. Manna in the wilderness and Passover themes echo as he claims to be God's sustaining provision for eternal life.</p>",
     "<p>The crowd seeks more signs; Jesus redirects them from perishable bread to the bread God gives from heaven. He identifies himself as that bread come down to give life to the world.</p>",
     ["What spiritual hunger are you trying to satisfy elsewhere?", "What does coming to Jesus daily look like for you?", "How is Jesus better than the 'bread' the world offers?"]),
    (181, 43, 7, 24,
     "Stop judging by mere appearances, but instead judge correctly.",
     "<p>During the Feast of Tabernacles in Jerusalem, debate swirls around Jesus' origin and authority. Religious leaders judge by surface rules while missing God's work in their midst.</p>",
     "<p>After brothers urge Jesus to show himself publicly, he teaches in the temple. He challenges superficial verdicts about his ministry and calls for righteous judgment aligned with God's law.</p>",
     ["Where are you tempted to judge by appearances?", "How can you discern God's work more carefully?", "What would 'judging correctly' change in a current conflict?"]),
    (182, 43, 8, 12,
     "When Jesus spoke again to the people, he said, \"I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.\"",
     "<p>Jesus teaches in the temple during the Feast of Tabernacles when giant lamps illuminated the courts. He claims to fulfill the festival's light imagery as the one who dispels moral and spiritual darkness.</p>",
     "<p>After forgiving a woman caught in adultery, Jesus resumes teaching. Pharisees challenge his testimony, but he declares himself the light guiding those who follow him out of darkness.</p>",
     ["What darkness are you walking in that Jesus wants to illuminate?", "What does following the light cost in your culture?", "How can you reflect Christ's light to others?"]),
    (183, 43, 11, 35,
     "Jesus wept.",
     "<p>At Lazarus's tomb near Bethany, Jesus faces grief two miles from Jerusalem where authorities plot his death. John's Gospel presents Jesus as fully divine yet deeply human in compassion.</p>",
     "<p>Martha and Mary mourn their brother four days dead. Jesus is deeply moved by their sorrow and the pain of death itself, weeping before commanding Lazarus to come out.</p>",
     ["How does knowing Jesus weeps change how you bring him your grief?", "When have you seen God's power joined with tender compassion?", "Who around you needs your tears as well as your strength?"]),
    (184, 43, 15, 13,
     "Greater love has no one than this: to lay down one's life for one's friends.",
     "<p>On the night before crucifixion, Jesus teaches disciples in the upper room. Vine and branches imagery prepares them for his departure and the cost of love within the new covenant community.</p>",
     "<p>After calling disciples friends who know the Father's business, Jesus contrasts hired hands with the good shepherd who dies for the sheep, defining ultimate love as self-giving unto death.</p>",
     ["Who has laid down their life for you — literally or figuratively?", "How are you called to sacrificial love in ordinary life?", "What does friendship with Jesus require of you?"]),
    (185, 43, 17, 3,
     "Now this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent.",
     "<p>Jesus prays in John 17 on the eve of the cross — the high priestly prayer. Eternal life in John's theology is relational knowledge of the Father and Son, not merely unending duration.</p>",
     "<p>Jesus prays for glory to return and for disciples to be protected and united. He defines eternal life as knowing the only true God and the sent Son — intimate, covenantal relationship.</p>",
     ["How is knowing God different from knowing about God?", "What practices deepen your knowledge of Christ?", "How does eternal life start now rather than only after death?"]),
    (186, 43, 20, 31,
     "But these are written that you may believe that Jesus is the Messiah, the Son of God, and that by believing you may have life in his name.",
     "<p>John writes decades after the resurrection for communities needing assurance that Jesus fulfills Scripture as Christ and Son of God. Signs in the Gospel point beyond themselves to faith and life.</p>",
     "<p>After the resurrection appearances and Peter's restoration, John states his selective purpose: signs recorded to produce belief in Jesus as Messiah and Son of God, resulting in life in his name.</p>",
     ["Which sign or story in John has most strengthened your faith?", "What does believing Jesus is the Messiah change in daily life?", "How does life in his name shape your identity?"]),
    (187, 44, 1, 8,
     "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.",
     "<p>Acts opens with the risen Jesus commissioning apostles before ascending from the Mount of Olives. The Spirit-empowered church will spread from Jewish Jerusalem across ethnic boundaries to the Gentile world.</p>",
     "<p>After forty days teaching about the kingdom, Jesus answers disciples' questions about timing. He promises the Spirit's power and maps the geographic expansion of gospel witness.</p>",
     ["Where is your 'Jerusalem' — your immediate witness field?", "How have you experienced the Spirit's power for witness?", "What step toward 'the ends of the earth' can your church take?"]),
    (188, 44, 2, 38,
     "Peter replied, \"Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.\"",
     "<p>At Pentecost in Jerusalem, Peter preaches to Jews from every nation. The Spirit falls, Peter proclaims crucified Jesus as Lord and Christ, and three thousand respond in a founding moment of the church.</p>",
     "<p>Cut to the heart by Peter's sermon, the crowd asks what to do. Peter calls for repentance, baptism in Jesus' name, forgiveness, and reception of the promised Spirit for all whom the Lord calls.</p>",
     ["What does repentance look like as an ongoing posture?", "How do baptism and forgiveness belong together in your story?", "How have you experienced the Holy Spirit as gift?"]),
    (189, 44, 4, 12,
     "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved.",
     "<p>Peter and John heal a lame man at the temple gate, provoking Sanhedrin arrest. Before Jewish leaders, Peter proclaims Jesus' exclusive saving authority in a pluralistic religious capital.</p>",
     "<p>After the healing, Peter preaches in Solomon's Colonnade that the crucified Jesus is the stone the builders rejected. Before the council, he boldly declares salvation's exclusivity in Jesus' name.</p>",
     ["How do you hold exclusivity in Christ with love for neighbors of other faiths?", "What does salvation in Jesus' name mean practically?", "When have you needed boldness like Peter's?"]),
    (190, 44, 5, 20,
     "\"Go, stand in the temple courts,\" he said, \"and tell the people all about this new life.\"",
     "<p>Angels free apostles imprisoned by the Sanhedrin after continued preaching despite orders to stop. The early church faces increasing pressure yet obeys God rather than human authorities.</p>",
     "<p>At night an angel opens prison doors and sends apostles back to the temple at dawn. They are to proclaim the full message of this new life in Christ to worshipers in the courts.</p>",
     ["What is 'new life' in Christ that you can articulate to others?", "When does obedience to God conflict with human authority?", "How does your community proclaim hope in public spaces?"]),
    (191, 44, 7, 55,
     "But Stephen, full of the Holy Spirit, looked up to heaven and saw the glory of God, and Jesus standing at the right hand of God.",
     "<p>Stephen, one of seven table servants, becomes the first Christian martyr in Jerusalem. His sermon recounts Israel's resistance to God's messengers, climaxing in vision of glorified Jesus.</p>",
     "<p>Before the council, Stephen rehearses Abraham to Moses to prophets who foretold the Righteous One. Enraged leaders drag him out to stone him as he sees heaven opened and Jesus standing.</p>",
     ["What does seeing Jesus 'standing' suggest about his welcome of martyrs?", "How does Stephen's forgiveness echo Jesus on the cross?", "What courage does the Spirit provide in persecution?"]),
    (192, 44, 9, 31,
     "Then the church throughout Judea, Galilee and Samaria enjoyed a time of peace and was strengthened. Living in the fear of the Lord and encouraged by the Holy Spirit, it increased in numbers.",
     "<p>After Saul's conversion and Peter's ministry to Cornelius, the church spreads beyond Jerusalem. Luke notes regional growth amid earlier persecution following Stephen's death.</p>",
     "<p>Saul preaches boldly in Damascus and Jerusalem; the church enjoys peace across Judea, Galilee, and Samaria. Reverent fear of God, Spirit encouragement, and numerical growth mark this season.</p>",
     ["What does 'fear of the Lord' look like in a healthy church?", "How has the Spirit encouraged you during hard seasons?", "What conditions help the church grow in faithfulness?"]),
    (193, 44, 10, 38,
     "how God anointed Jesus of Nazareth with the Holy Spirit and power, and how he went around doing good and healing all who were under the power of the devil, because God was with him.",
     "<p>Peter preaches in Caesarea Maritima to Gentile centurion Cornelius — a breakthrough in mission. Roman officers represented empire; Peter declares Jesus as Lord over spiritual oppression and sickness.</p>",
     "<p>After Cornelius's vision and Peter's rooftop revelation, Peter enters a Gentile home and summarizes Jesus' ministry from John's baptism through crucifixion and resurrection, emphasizing Spirit-anointed good works.</p>",
     ["How did Jesus' doing good challenge religious boundaries?", "Where do you see people under the devil's power needing Christ?", "What does God's presence with Jesus promise for your service?"]),
    (194, 44, 16, 31,
     "They replied, \"Believe in the Lord Jesus, and you will be saved—you and your household.\"",
     "<p>Paul and Silas are imprisoned in Philippi after freeing a slave girl from a spirit. A Macedonian jailer, fearing punishment after an earthquake opens cells, asks how to be saved in a pagan colony.</p>",
     "<p>Paul and Silas sing at midnight; an earthquake loosens chains. The jailer nearly kills himself, but Paul assures no one escaped. Trembling, he asks about salvation and receives the gospel for his household.</p>",
     ["How does belief in the Lord Jesus reshape a whole household?", "What role do worship and integrity play in witness?", "Who in your 'household' needs to hear the gospel?"]),
    (195, 45, 1, 16,
     "For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes: first to the Jew, then to the Gentile.",
     "<p>Paul writes to Rome from Corinth around AD 57, introducing his magnum opus on righteousness by faith. The gospel was foolishness to Greeks and a stumbling block to Jews, yet Paul boasts in its saving power.</p>",
     "<p>After greeting the Roman church and expressing his desire to visit, Paul states he is eager to preach in Rome. He is unashamed because the gospel is God's power for salvation to all who believe.</p>",
     ["When have you felt ashamed of the gospel?", "How have you seen the gospel's power change someone?", "What does 'first to the Jew, then to the Gentile' teach about mission?"]),
    (196, 45, 4, 7,
     "Blessed are those whose transgressions are forgiven, whose sins are covered.",
     "<p>Paul argues in Romans 4 that Abraham was justified by faith before circumcision, making him father of all who believe. He cites David's psalm celebrating forgiveness apart from works.</p>",
     "<p>Using Abraham and David as witnesses, Paul shows righteousness credited apart from law. David describes the blessedness of the person whose lawless deeds are forgiven and whose sin is covered.</p>",
     ["How does forgiven sin feel different from hidden guilt?", "Why is faith rather than performance the basis of blessing?", "Who needs to hear that their transgressions can be covered?"]),
    (197, 45, 5, 1,
     "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ",
     "<p>Romans 5 bridges justification by faith with hope in suffering. Paul writes to believers who need assurance that reconciliation with God is secure through Christ's death and resurrection.</p>",
     "<p>After showing Abraham's faith credited as righteousness, Paul declares benefits of justification: peace with God, access to grace, and rejoicing in hope of God's glory.</p>",
     ["What is the difference between peace with God and peaceful circumstances?", "How does justification by faith affect your confidence before God?", "Where do you need to rest in peace with God today?"]),
    (198, 45, 6, 14,
     "For sin shall no longer be your master, because you are not under the law, but under grace.",
     "<p>Paul addresses Christians tempted to sin because grace abounds. Baptism into Christ's death breaks sin's dominion; believers live under grace's empowering lordship rather than law's condemning pressure alone.</p>",
     "<p>Romans 6 teaches death to sin through union with Christ's death and resurrection. Paul concludes that sin must not reign in mortal bodies because believers are under grace, not law as mere master.</p>",
     ["What sins still feel like a master in your life?", "How does being under grace empower holiness?", "What does it mean that you died to sin in baptism?"]),
    (199, 45, 8, 31,
     "What, then, shall we say in response to these things? If God is for us, who can be against us?",
     "<p>Romans 8 culminates Paul's teaching on life in the Spirit amid suffering. Early Christians faced opposition from synagogue and state; Paul anchors assurance in God's unstoppable love in Christ.</p>",
     "<p>After promises that all things work for good and that nothing separates us from God's love, Paul poses a rhetorical question: if God is for us, who can successfully oppose his people?</p>",
     ["What 'things' make you doubt that God is for you?", "How does Romans 8 reshape your view of suffering?", "Who or what feels 'against you' that God outweighs?"]),
    (200, 45, 10, 13,
     "for, \"Everyone who calls on the name of the Lord will be saved.\"",
     "<p>Paul grieves Israel's unbelief while insisting the gospel is near — in the mouth and heart. He cites Joel 2 to show salvation is available to everyone who calls on the Lord's name.</p>",
     "<p>Romans 10 contrasts righteousness by faith with pursuing law-based righteousness. Paul quotes Scripture to promise that all who call on the name of the Lord will be saved.</p>",
     ["What does calling on the Lord's name look like in crisis?", "Who around you needs to hear this promise?", "How can your church remove barriers to calling on Christ?"]),
]

# Lessons 201-278 continue in second batch
LESSONS_2 = [
    (201, 45, 12, 1,
     "Therefore, I urge you, brothers and sisters, in view of God's mercy, to offer your bodies as a living sacrifice, holy and pleasing to God—this is your true and proper worship.",
     "<p>Romans 12 begins the ethical section rooted in God's mercies in chapters 1–11. In a culture of temple sacrifice, Paul calls for whole-life worship — bodies presented daily to God.</p>",
     "<p>After eleven chapters of doctrine, Paul turns to response: do not conform to the age but be transformed. Presenting bodies as living sacrifices is logical worship in light of mercy received.</p>",
     ["What would offering your body as a living sacrifice look like this week?", "How is daily obedience a form of worship?", "What patterns of the world do you need to resist?"]),
    (202, 45, 13, 8,
     "Let no debt remain outstanding, except the continuing debt to love one another, for whoever loves others has fulfilled the law.",
     "<p>Paul writes to Christians in the capital of empire about civil obedience and neighbor love. Roman society ran on debt and patronage; Paul names love as the one obligation that never ends.</p>",
     "<p>After teaching submission to governing authorities and paying taxes, Paul summarizes the commandments as fulfilled in love of neighbor. Only the debt to love remains permanently outstanding.</p>",
     ["Who is hardest for you to love consistently?", "How does love fulfill the law without ignoring justice?", "What 'debts' distract you from loving others?"]),
    (203, 45, 14, 8,
     "If we live, we live for the Lord; and if we die, we die for the Lord. So, whether we live or die, we belong to the Lord.",
     "<p>Romans 14–15 addresses disputes over food and sacred days in a mixed Jewish-Gentile church. Paul grounds unity in Christ's lordship over each believer's life and death.</p>",
     "<p>Paul urges acceptance of weaker brothers and sisters and refrains from judging. Whether we live or die, believers belong to the Lord who died and rose to be Lord of all.</p>",
     ["How does belonging to the Lord change your daily decisions?", "What disputes in church life need Christ's lordship?", "How can you honor others whose convictions differ from yours?"]),
    (204, 45, 15, 4,
     "For everything that was written in the past was written to teach us, so that through the endurance taught in the Scriptures and the encouragement they provide we might have hope.",
     "<p>Paul cites Old Testament examples to build unity between strong and weak believers. Scripture functions as instructive narrative producing endurance, encouragement, and hope for the church.</p>",
     "<p>Paul notes Christ welcomed them as Scripture promised. Everything written beforehand was for their instruction, that through endurance and encouragement of the Scriptures they might have hope.</p>",
     ["What Old Testament story has most encouraged your endurance?", "How does Scripture produce hope in discouraging seasons?", "Who needs you to share biblical encouragement?"]),
    (205, 46, 1, 18,
     "For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.",
     "<p>Paul writes to Corinth, a proud commercial city valuing rhetoric and wisdom. The crucified Messiah overturns human standards of power and status, dividing responders into those perishing and those being saved.</p>",
     "<p>After greeting a divided church, Paul refuses to preach with eloquent wisdom lest the cross be emptied. To the perishing the cross is folly; to believers it is God's saving power.</p>",
     ["When has the cross seemed foolish to people around you?", "How has the cross been God's power in your life?", "What worldly wisdom competes with the gospel in your church?"]),
    (206, 46, 2, 9,
     "However, as it is written: \"What no eye has seen, what no ear has heard, and what no human mind has conceived\"—the things God has prepared for those who love him—",
     "<p>Paul contrasts Spirit-revealed wisdom with human philosophy. Isaiah 64:4 provides language for blessings God has prepared for lovers of God — realities only the Spirit discerns.</p>",
     "<p>Paul insists the rulers of this age did not understand God's hidden wisdom in the cross. God prepared glorious things beyond human perception, now revealed to those who love him by the Spirit.</p>",
     ["What has the Spirit revealed to you that reason alone could not?", "How does future hope shape present faithfulness?", "What does loving God look like in ordinary routines?"]),
    (207, 46, 10, 13,
     "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.",
     "<p>Corinthian believers faced idolatry and moral pressure in a pagan city. Paul warns against overconfidence using Israel's wilderness failures, then assures God's faithful limits and escape in temptation.</p>",
     "<p>After examples of Israel's testing, Paul warns against idolatry. He promises temptations are common, God is faithful, temptation is bounded, and a way of endurance is always provided.</p>",
     ["What temptation feels unique or overwhelming to you right now?", "Where might God be providing a way out you have overlooked?", "How does God's faithfulness change your fight against sin?"]),
    (208, 46, 13, 4,
     "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.",
     "<p>1 Corinthians 13 follows Paul's teaching on spiritual gifts in a status-conscious church. Agape love — God's own character in action — is the indispensable virtue without which gifts are noise.</p>",
     "<p>Paul elevates love above tongues, prophecy, and knowledge. He begins his famous hymn by describing love's patience, kindness, and freedom from envy, boasting, and pride.</p>",
     ["Which quality of love — patience, kindness, humility — do you most need to grow?", "When have gifts been used without love in your experience?", "How does this verse redefine success in ministry?"]),
    (209, 46, 15, 10,
     "But by the grace of God I am what I am, and his grace to me was not without effect. No, I worked harder than all of them—yet not I, but the grace of God that was with me.",
     "<p>Paul defends resurrection hope against Corinthian skeptics. He grounds his apostleship and labor in grace that both transforms identity and energizes strenuous gospel work.</p>",
     "<p>After listing resurrection witnesses including himself as one abnormally born, Paul attributes his being and labor to grace. Hard work and divine grace are not opponents but partners.</p>",
     ["How has grace shaped who you are?", "Do you tend to boast in effort or dismiss effort because of grace?", "Where is God's grace producing visible effect in your life?"]),
    (210, 46, 15, 55,
     "\"Where, O death, is your victory? Where, O death, is your sting?\"",
     "<p>Paul's resurrection chapter taunts death with Hosea's victory language. Christian hope at Corinth challenged by Greek disdain for bodily resurrection finds triumph in Christ the firstfruits.</p>",
     "<p>After describing the resurrection body and victory over the last enemy, Paul quotes Scripture mockingly: death's sting is sin, sin's power is law, but thanks be to God who gives victory through Jesus.</p>",
     ["How does resurrection hope change how you face mortality?", "What 'sting' of death do you feel in loss or fear?", "How can you proclaim Christ's victory to grieving people?"]),
    (211, 47, 5, 17,
     "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!",
     "<p>Paul ministers reconciliation to Corinthians amid broken relationships and suspicion of his ministry. In Christ, God inaugurates new-creation reality that redefines identity and mission.</p>",
     "<p>Paul teaches that God reconciled the world in Christ and entrusted believers with the message of reconciliation. Anyone in Christ participates in new creation — old passed away, new arrived.</p>",
     ["What 'old' patterns has Christ begun to replace in you?", "How does being new creation affect how you see others?", "What does reconciliation look like in a broken relationship?"]),
    (212, 47, 9, 6,
     "Remember this: Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously.",
     "<p>Paul urges Corinthian generosity for Jerusalem saints facing famine. Ancient sowing imagery communicates that giving reflects trust in God's provision and yields spiritual harvest.</p>",
     "<p>Paul commends Macedonian churches' extreme generosity and encourages Corinth to excel in the grace of giving. He applies agricultural principle: sowing and reaping correspond in measure.</p>",
     ["Where is God inviting you to sow generously?", "How does generosity express trust in God's provision?", "What harvest might God produce through your giving?"]),
    (213, 47, 12, 9,
     "But he said to me, \"My grace is sufficient for you, for my power is made perfect in weakness.\" Therefore I will boast all the more gladly about my weaknesses, so that Christ's power may rest on me.",
     "<p>Paul describes a 'thorn in the flesh' amid visions of paradise. Corinth's culture prized strength; Paul learns Christ's power shines through admitted weakness rather than self-sufficiency.</p>",
     "<p>After boasting reluctantly in visions, Paul tells of a painful thorn and pleas for removal. Christ answers that grace suffices and power perfects in weakness, reshaping Paul's boasting.</p>",
     ["What weakness do you try to hide that God might use?", "How have you experienced sufficient grace in hardship?", "What would boasting in weakness look like in your community?"]),
    (214, 48, 2, 20,
     "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.",
     "<p>Paul confronts Peter's hypocrisy in Antioch over table fellowship with Gentiles. Justification by faith alone excludes boasting in law-keeping; union with Christ replaces self-directed life.</p>",
     "<p>Paul rebukes Peter for withdrawing from Gentiles. He declares crucifixion with Christ ends self-life; now Christ lives in him and bodily life flows from faith in the Son who loved and gave himself.</p>",
     ["What does it mean that you no longer live but Christ lives in you?", "Where are you tempted back toward performance-based acceptance?", "How does personal love ('who loved me') motivate your faith?"]),
    (215, 48, 5, 1,
     "It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.",
     "<p>Galatians battles Judaizers demanding circumcision for Gentile believers. Paul insists freedom in Christ is the goal of redemption, not liberty to sin but release from law-as-basis-for-acceptance slavery.</p>",
     "<p>After allegory of Hagar and Sarah, Paul exhorts believers to stand in freedom. Christ freed them for freedom itself — they must not submit again to slavery's yoke.</p>",
     ["What yoke of slavery — legalism, sin, approval — tempts you back?", "How is Christian freedom different from doing whatever you want?", "What does standing firm look like in your context?"]),
    (216, 48, 6, 14,
     "May I never boast except in the cross of our Lord Jesus Christ, through which the world has been crucified to me, and I to the world.",
     "<p>Paul closes Galatians emphasizing new creation and the cross as sole ground of glory. Circumcision debates fade before the world-crucifying power of Christ's cross.</p>",
     "<p>Paul rejects boasting in circumcision or flesh. His only boast is the cross, which ended the world's hold on him and his conformity to worldly standards.</p>",
     ["What do you boast in besides the cross?", "How has the cross crucified worldly ambitions in you?", "How can your community center conversation on the cross?"]),
    (217, 49, 1, 3,
     "Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.",
     "<p>Ephesians is likely a circular letter to churches in Asia Minor, celebrating God's cosmic plan in Christ. Paul opens with a Jewish-style berakah blessing God for spiritual riches in the heavenly realms.</p>",
     "<p>Before detailing election, redemption, and unity, Paul blesses the Father who has already blessed believers with every spiritual blessing in Christ in heavenly places.</p>",
     ["Which spiritual blessing in Christ do you most need to remember?", "How does praise at the start of prayer reshape your perspective?", "What does 'in heavenly realms' suggest about your present standing?"]),
    (218, 49, 4, 4,
     "There is one body and one Spirit, just as you were called to one hope when you were called",
     "<p>Ephesians 4 urges unity in a diverse church facing cultural and social divisions. Seven 'ones' anchor identity: one body, Spirit, hope, Lord, faith, baptism, and God.</p>",
     "<p>Paul exhorts worthy living according to calling, with humility and patience. He lists foundational unities beginning with one body and one Spirit joined to one hope of calling.</p>",
     ["What threatens unity in your church or group?", "How does shared hope overcome differences?", "What practice helps you preserve the Spirit's unity?"]),
    (219, 49, 5, 1,
     "Follow God's example, therefore, as dearly loved children",
     "<p>Ephesians 5 calls believers to imitate God as beloved children. In a Greco-Roman world of patron gods and moral confusion, Paul roots ethics in the Father's love and forgiving character.</p>",
     "<p>After urging forgiveness as God in Christ forgave, Paul calls believers to walk in love as Christ loved and gave himself. They are to imitate God as dear children.</p>",
     ["What attribute of God — love, forgiveness, holiness — are you called to imitate now?", "How does being 'dearly loved' empower obedience?", "Who models God's example for you?"]),
    (220, 50, 1, 21,
     "For to me, to live is Christ and to die is gain.",
     "<p>Paul writes Philippians from prison, partnering with a church he loves in a Roman colony. His life calculus centers on Christ whether in ministry or martyrdom.</p>",
     "<p>Paul discusses his struggle between departing to be with Christ or remaining for the church's progress. He summarizes his outlook: living means Christ; dying is gain.</p>",
     ["What would it mean for you to say 'to live is Christ'?", "Why might Paul call death 'gain' without despising life?", "How does eternal perspective change daily choices?"]),
    (221, 50, 2, 5,
     "In your relationships with one another, have the same mindset as Christ Jesus:",
     "<p>Philippians 2 addresses rivalry and self-interest in the church. Paul introduces the Christ hymn, calling for humility modeled on Jesus' incarnation and obedient death.</p>",
     "<p>After urging unity and humble regard for others above yourselves, Paul commands the Christ-like mindset that the following verses describe in Jesus' self-emptying and exaltation.</p>",
     ["Where do you need Christ's mindset in a relationship?", "What does putting others first cost you?", "How does the incarnation inspire your humility?"]),
    (222, 50, 3, 13,
     "Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead,",
     "<p>Paul warns against confidence in fleshly credentials — pedigree, zeal, righteousness. He presses toward resurrection perfection with athletic imagery familiar in Greek games.</p>",
     "<p>Paul counts former gains as loss for knowing Christ. Not yet perfect, he forgets what lies behind and strains forward to the goal of God's upward call in Christ.</p>",
     ["What from your past do you need to leave behind?", "What goal is God calling you to strain toward?", "How does 'not yet' keep you humble and hungry?"]),
    (223, 51, 1, 15,
     "The Son is the image of the invisible God, the firstborn over all creation.",
     "<p>Colossians combats teaching that diminishes Christ's supremacy in a syncretistic culture. Paul presents Christ as visible image of invisible God and preeminent over creation.</p>",
     "<p>After thanksgiving and prayer, Paul describes Christ's cosmic role: image of God, firstborn over creation, creator and sustainer, head of the church, firstborn from the dead.</p>",
     ["How does Christ as God's image clarify who God is?", "What false teachings today diminish Christ's supremacy?", "How does creation's dependence on Christ affect your worship?"]),
    (224, 51, 2, 6,
     "So then, just as you received Christ Jesus as Lord, continue to live in him,",
     "<p>Paul warns Colossae against hollow philosophy and human tradition. Reception of Christ as Lord demands ongoing rooted, built-up life rather than one-time decision.</p>",
     "<p>After celebrating fullness in Christ and victory over powers, Paul urges believers to walk in Christ as they received him — continuing to live in him with roots and growth.</p>",
     ["How did you first receive Christ as Lord?", "What helps you continue living in him daily?", "What philosophies pull you away from rooted life in Christ?"]),
    (225, 51, 3, 1,
     "Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God.",
     "<p>Colossians 3 applies resurrection union ethically. Believers died and rose with Christ; therefore heavenly orientation reshapes desires, ethics, and community life.</p>",
     "<p>Paul commands putting to death earthly members and putting on new self. Because you were raised with Christ, seek the things above where Christ sits at God's right hand.</p>",
     ["What earthly things compete for your heart's attention?", "How does Christ's seated authority encourage you?", "What 'things above' should shape your priorities this week?"]),
    (226, 51, 3, 16,
     "Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns, and songs from the Spirit, singing to God with gratitude in your hearts.",
     "<p>Household codes follow in Colossae's setting of domestic and social order. Paul envisions community saturated with Christ's word through teaching, correction, and Spirit-filled worship.</p>",
     "<p>After putting on compassion and forgiveness, Paul calls the word of Christ to dwell richly. Teaching, admonition, and grateful psalms, hymns, and spiritual songs mark the community.</p>",
     ["How richly does Christ's message dwell in your home or group?", "What role should singing play in your discipleship?", "Who can you teach or admonish with wisdom this week?"]),
    (227, 51, 4, 5,
     "Be wise in the way you act toward outsiders; make the most of every opportunity.",
     "<p>Paul closes with practical household and mission instructions. Outsiders watch Christian behavior; redeemed time becomes witness opportunity in a watching world.</p>",
     "<p>After prayer and thanksgiving instructions, Paul urges gracious speech seasoned with salt. Believers must walk wisely toward outsiders and redeem the time.</p>",
     ["Who are the 'outsiders' observing your life?", "What opportunity for witness might you be missing?", "How can speech be both gracious and salty?"]),
    (228, 52, 1, 3,
     "We remember before our God and Father your work produced by faith, your labor prompted by love, and your endurance inspired by hope in our Lord Jesus Christ.",
     "<p>Paul writes to Thessalonica where converts faced persecution soon after his brief ministry. The triad of faith, love, and hope marks authentic Christian community under pressure.</p>",
     "<p>Paul thanks God for the church's election and gospel reception in power. He remembers their faith-work, love-labor, and hope-endurance before God.</p>",
     ["Which of faith, love, or hope needs strengthening in you?", "How does persecution refine genuine devotion?", "Who can you thank God for in your church?"]),
    (229, 52, 2, 19,
     "For what is our hope, our joy, or the crown in which we will glory in the presence of our Lord Jesus when he comes? Is it not you?",
     "<p>Paul defends his tender pastoral labor against opponents in Thessalonica. Apostolic reward is not status but people presented as crown of boasting at Christ's parousia.</p>",
     "<p>Paul compares his gentle nursing among them to a father's encouragement. At Christ's coming, they themselves are his hope, joy, and glory crown.</p>",
     ["Who has invested in your faith like Paul did in Thessalonica?", "How does future glory motivate present pastoral care?", "Whose crown might you be helping to form?"]),
    (230, 52, 4, 16,
     "For the Lord himself will come down from heaven, with a loud command, with the voice of the archangel and with the trumpet call of God, and the dead in Christ will rise first.",
     "<p>Thessalonians grieved deaths of believers before Christ's return. Paul comforts them with vivid apocalyptic imagery of personal, vocal, triumphant coming and resurrection priority.</p>",
     "<p>Paul urges grief with hope, not ignorance. The Lord will descend with command, archangel's voice, and trumpet; dead in Christ rise first, then living believers meet the Lord.</p>",
     ["How does resurrection hope comfort you in loss?", "What does the Lord's personal coming mean to you?", "How should this hope shape daily holiness?"]),
    (231, 52, 5, 11,
     "Therefore encourage one another and build each other up, just as in fact you are doing.",
     "<p>1 Thessalonians 5 follows 'day of the Lord' teaching like a thief. Community response to uncertain times is mutual encouragement and edification, continuing existing good practice.</p>",
     "<p>After urging sober readiness for the day of the Lord, Paul lists honor, peace, and patience. He commands encouragement and building up, affirming they already do so.</p>",
     ["Who needs your encouragement this week?", "How can you build others up in faith?", "What edifying practice is your group already doing well?"]),
    (232, 53, 1, 5,
     "All this is evidence that God's judgment is right, and as a result you will be counted worthy of the kingdom of God, for which you are also suffering.",
     "<p>2 Thessalonians addresses persecution and misunderstandings about the day of the Lord. Paul assures suffering believers that God's righteous judgment will vindicate them and afflict oppressors.</p>",
     "<p>Paul gives thanks for their perseverance and faith amid affliction. Their suffering is evidence of God's righteous judgment and worthiness for God's kingdom.</p>",
     ["How do you reconcile suffering with God's righteous judgment?", "What helps you endure persecution or hardship?", "How is the kingdom worth present suffering?"]),
    (233, 53, 2, 13,
     "But we ought always to thank God for you, brothers and sisters loved by the Lord, because God chose you as firstfruits to be saved through the sanctifying work of the Spirit and through belief in the truth.",
     "<p>Paul comforts Thessalonians anxious about end-times deception. Election language here highlights gratitude and holiness — chosen for salvation through Spirit-sanctification and truth-belief.</p>",
     "<p>After warning about the lawless one, Paul thanks God for beloved believers chosen as firstfruits, saved through the Spirit's sanctifying work and belief in truth.</p>",
     ["How does thankfulness follow from being loved and chosen?", "What does Spirit-sanctification look like in your growth?", "How does truth-belief guard against deception?"]),
    (234, 53, 3, 3,
     "But the Lord is faithful, and he will strengthen you and protect you from the evil one.",
     "<p><em>Note: corrected from invalid 2 Thessalonians 4:3.</em> Paul closes with prayer against idleness and requests prayer for his ministry. The Lord's faithfulness guarantees strength and protection from Satan.</p>",
     "<p>After commanding discipline for disorderly believers and warning against idleness, Paul assures that the faithful Lord will strengthen and guard them from the evil one.</p>",
     ["Where do you need the Lord's strengthening today?", "How have you experienced protection from evil?", "What does God's faithfulness promise when you feel weak?"]),
    (235, 53, 3, 5,
     "May the Lord direct your hearts into God's love and Christ's perseverance.",
     "<p><em>Note: corrected from invalid 2 Thessalonians 5:8.</em> Paul's benedictory prayer asks the Lord to orient hearts toward divine love and steadfast endurance modeled in Christ.</p>",
     "<p>Paul prays that the Lord would direct hearts into the love of God and the perseverance of Christ — twin graces needed for faithful endurance until Christ returns.</p>",
     ["How can you ask God to direct your heart toward his love?", "What does Christ's perseverance teach about enduring hardship?", "Who can you pray this blessing over?"]),
    (236, 54, 1, 15,
     "Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners—of whom I am the worst.",
     "<p>Paul writes 1 Timothy to guide church order in Ephesus amid false teaching. The trustworthy saying summarizes the gospel Paul embodies as former blasphemer now displaying God's patience.</p>",
     "<p>Paul urges Timothy to wage good warfare holding faith and good conscience. He cites the trustworthy saying that Christ came to save sinners, naming himself worst.</p>",
     ["Why does Paul call himself the worst sinner?", "How does this saying anchor gospel ministry?", "Who needs to hear that Christ came to save sinners like them?"]),
    (237, 54, 2, 1,
     "I urge, then, first of all, that petitions, prayers, intercession and thanksgiving be made for all people—",
     "<p>1 Timothy 2 links prayer for all people — including rulers — with peaceful gospel advance. Roman emperors and local authorities held life-and-death power over churches.</p>",
     "<p>Paul's first charge is that petitions, prayers, intercession, and thanksgiving be made for everyone, enabling quiet, godly lives as God desires all to be saved.</p>",
     ["For which leaders or difficult people do you struggle to pray?", "How does prayer for all people advance the gospel?", "What thanksgiving can you offer for people unlike you?"]),
    (238, 54, 4, 12,
     "Don't let anyone look down on you because you are young, but set an example for the believers in speech, in conduct, in love, in faith and in purity.",
     "<p>Timothy, likely in his thirties, leads in a culture honoring age. Paul counters age-based contempt with exemplary speech, conduct, love, faith, and purity.</p>",
     "<p>After warning about deceiving spirits and forbidding marriage, Paul gives Timothy personal charges including public reading, gifting, and not letting youth be despised but becoming a model believer.</p>",
     ["How can younger believers lead with credibility?", "Which area — speech, conduct, love, faith, purity — needs attention?", "How can older believers encourage rather than dismiss youth?"]),
    (239, 54, 6, 12,
     "Fight the good fight of the faith. Take hold of the eternal life to which you were called when you made your good confession in the presence of many witnesses.",
     "<p>Paul closes 1 Timothy warning against love of money. Athletic and military metaphors frame Timothy's call to guard the gospel deposit with courage and integrity.</p>",
     "<p>After charging the rich and urging Timothy to flee love of money, Paul commands fighting the good fight, taking hold of eternal life confessed before witnesses.</p>",
     ["What does fighting the good fight look like in your setting?", "How does your public confession shape present faithfulness?", "What temptations rival taking hold of eternal life?"]),
    (240, 55, 1, 7,
     "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.",
     "<p>2 Timothy is Paul's final letter from prison before execution. Timothy faces shame and fear; Paul reminds him the indwelling Spirit produces power, love, and self-control, not cowardice.</p>",
     "<p>Paul urges Timothy to fan into flame the gift received through laying on of hands. The Spirit given is not timidity but power, love, and self-discipline for gospel witness.</p>",
     ["Where has fear silenced your witness?", "How do power, love, and self-discipline work together?", "What gift needs fanning into flame in your life?"]),
    (241, 55, 3, 16,
     "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness,",
     "<p>Paul warns of terrible times and corrupt teachers. Scripture — particularly the sacred writings Timothy knew from childhood — is breathed-out by God and fully equips the man or woman of God.</p>",
     "<p>After describing perilous people and Jannes and Jambres, Paul affirms all Scripture is God-breathed, profitable for teaching, rebuke, correction, and righteousness training.</p>",
     ["How do you use Scripture for more than information?", "When has God's Word corrected or trained you?", "What false teaching makes this verse urgent today?"]),
    (242, 55, 4, 7,
     "I have fought the good fight, I have finished the race, I have kept the faith.",
     "<p>Paul's swan song near death uses games and battle imagery. His life review centers on faithfulness to Christ's deposit rather than earthly survival or acclaim.</p>",
     "<p>Knowing his departure is near and a crown awaits, Paul reflects on completed struggle: good fight fought, race finished, faith kept — with confidence in the righteous Judge.</p>",
     ["What fight, race, or faith journey are you in now?", "How do you want to finish your course?", "What crown of righteousness motivates endurance?"]),
    (243, 56, 2, 11,
     "For the grace of God has appeared that offers salvation to all people.",
     "<p>Titus ministers in Crete, stereotyped in antiquity for moral laxity. Paul grounds ethical instruction in the appearing grace of God that brings salvation to all people.</p>",
     "<p>After listing qualifications for elders, Paul teaches sound doctrine. God's grace has appeared bringing salvation to all, teaching us to say no to ungodliness.</p>",
     ["How has God's appearing grace changed your lifestyle?", "What does salvation offered to all people imply for mission?", "How does grace teach renunciation of ungodliness?"]),
    (244, 56, 3, 5,
     "he saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit,",
     "<p>Titus 3 contrasts former foolish, enslaved life with God's mercy. Salvation is not earned by righteous deeds but granted through rebirth-washing and Spirit-renewal.</p>",
     "<p>Paul reminds believers of pre-Christ alienation and hatred. God saved them not by works of righteousness but by mercy, through washing of rebirth and renewing Holy Spirit.</p>",
     ["How does mercy-based salvation humble pride?", "What does rebirth and renewal mean in your experience?", "How should saved people treat outsiders differently?"]),
    (245, 57, 1, 6,
     "I pray that your partnership with us in the faith may be effective in deepening your understanding of every good thing we share for the sake of Christ.",
     "<p>Philemon is Paul's shortest letter, appealing for runaway slave Onesimus now converted. Partnership (<em>koinonia</em>) in faith should deepen knowledge of every good thing shared in Christ.</p>",
     "<p>Paul thanks God for Philemon's love and faith toward saints. He prays that sharing in faith may become effective in full knowledge of every good thing in them for Christ.</p>",
     ["How does partnership in faith deepen understanding?", "What good things do you share with believers for Christ's sake?", "How might reconciliation display gospel partnership?"]),
    (246, 58, 4, 12,
     "For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart.",
     "<p>Hebrews warns Jewish-background believers tempted to drift from Christ. Scripture is not dead letter but living, piercing divine speech exposing inner motives.</p>",
     "<p>After warning about failing to enter God's rest through unbelief, the author describes God's living word — sharper than any sword, discerning heart thoughts and intentions.</p>",
     ["When has Scripture exposed something hidden in your heart?", "Why is living and active better than merely ancient?", "How do you approach God's Word expecting discernment?"]),
    (247, 58, 4, 16,
     "Let us then approach God's throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.",
     "<p>Hebrews presents Jesus as great high priest after Melchizedek. Because he sympathizes with weakness yet is sinless, believers approach God's throne boldly for timely help.</p>",
     "<p>Jesus' priesthood surpasses Aaron's; he was tempted yet without sin. Therefore let us draw near the throne of grace with confidence to receive mercy and grace for need.</p>",
     ["What need drives you to God's throne today?", "How does Jesus' sympathy increase your confidence?", "What would bold prayer look like this week?"]),
    (248, 58, 10, 24,
     "And let us consider how we may spur one another on toward love and good deeds,",
     "<p>Hebrews 10 exhorts perseverance after describing Christ's once-for-all sacrifice. Mutual provocation toward love and good works replaces isolated, shrinking faith.</p>",
     "<p>After warning against willful sin and urging confidence, the author commands not neglecting meeting together. Consider how to spur one another to love and good deeds.</p>",
     ["Who spurs you on toward love and good deeds?", "How can you provoke others positively without nagging?", "Why is gathering together essential for this?"]),
    (249, 58, 11, 6,
     "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.",
     "<p>Hebrews 11's faith hall of fame begins with foundational definition. Pleasing God requires faith — existence trust and reward expectation for earnest seekers.</p>",
     "<p>The author introduces faith as assurance of hoped-for things and conviction of unseen realities. Without faith one cannot please God; seekers must believe he exists and rewards.</p>",
     ["Do you believe God rewards earnest seeking?", "What unseen realities anchor your faith?", "How does this verse define faith beyond mere opinion?"]),
    (250, 58, 13, 5,
     "Keep your lives free from the love of money and be content with what you have, because God has said, \"Never will I leave you; never will I forsake you.\"",
     "<p>Hebrews closes with practical exhortations for a suffering community. Contentment flows from God's covenant promise of presence, not from accumulating wealth.</p>",
     "<p>After brotherly love and hospitality, the author warns against loving money. Be content with what you have, for God has promised never to leave or forsake you.</p>",
     ["Where does love of money tempt you?", "How does God's presence enable contentment?", "What promise do you need to claim against anxiety?"]),
]

LESSONS_3 = [
    (251, 59, 1, 5,
     "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.",
     "<p>James writes to Jewish Christians scattered by persecution. Wisdom for trials is not earned by eloquence but received through single-minded prayer to a generous God.</p>",
     "<p>James opens with joy in trials producing perseverance. When lacking wisdom in hardship, ask God who gives generously to all without reproach, and it will be given.</p>",
     ["What decision requires God's wisdom right now?", "How have you experienced God giving without finding fault?", "What trials might God use to mature you?"]),
    (252, 59, 2, 17,
     "In the same way, faith by itself, if it is not accompanied by action, is dead.",
     "<p>James confronts favoritism and empty profession in diaspora churches. Genuine faith necessarily produces works, as body without spirit is dead.</p>",
     "<p>James illustrates faith and deeds with Abraham and Rahab. Faith alone without accompanying action is dead — like a corpse without breath.</p>",
     ["What action should your faith produce this week?", "How do works testify to faith without replacing grace?", "Where might your faith be 'dead' without realizing it?"]),
    (253, 59, 4, 10,
     "Humble yourselves before the Lord, and he will lift you up.",
     "<p>James 4 diagnoses quarrels rooted in selfish desires and friendship with the world. God opposes the proud but gives grace to the humble who submit to his lordship.</p>",
     "<p>After calling for repentance, cleansing, and mourning over sin, James commands humbling before the Lord with promise that he will exalt the humble.</p>",
     ["What pride keeps you from humbling before God?", "How have you seen God lift the humble?", "What would submission look like in a current conflict?"]),
    (254, 59, 5, 16,
     "Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective.",
     "<p>James closes addressing injustice, patience in suffering, and prayer. Community confession and intercession channel God's healing power through righteous prayer.</p>",
     "<p>After urging patience until the Lord's coming and warning the rich, James prescribes mutual confession and prayer for healing, noting Elijah-like power of righteous prayer.</p>",
     ["Who is a safe person for mutual confession and prayer?", "How does community prayer differ from private prayer?", "What healing — spiritual or physical — are you seeking?"]),
    (255, 60, 1, 3,
     "Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead,",
     "<p>1 Peter encourages believers suffering official suspicion in Asia Minor. New birth into living hope rests on Christ's resurrection, not shifting political fortunes.</p>",
     "<p>Peter blesses God for mercy granting new birth to living hope through Jesus' resurrection, to an inheritance kept in heaven, guarded through faith.</p>",
     ["How is your hope 'living' rather than wishful?", "What does resurrection-grounded hope change in suffering?", "How does new birth redefine your identity?"]),
    (256, 60, 2, 9,
     "But you are a chosen people, a royal priesthood, a holy nation, God's special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.",
     "<p>Peter applies Exodus and Isaiah language to Gentile-inclusive church. Identity as chosen priestly nation exists for proclaiming God's excellencies who rescued from darkness.</p>",
     "<p>After describing believers as living stones and spiritual house, Peter declares their corporate identity: chosen people, royal priesthood, holy nation, God's possession for praise declaration.</p>",
     ["How does being God's special possession shape daily choices?", "What praises of God can you declare to others?", "From what darkness has Christ called you?"]),
    (257, 60, 3, 15,
     "But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have. But do this with gentleness and respect,",
     "<p>1 Peter 3 addresses suffering for righteousness in hostile society. Inner allegiance to Christ as Lord prepares gracious, respectful defense of gospel hope before skeptics.</p>",
     "<p>After urging wives and husbands toward honorable conduct, Peter commands sanctifying Christ as Lord in hearts, ready to explain hope with gentleness and respect.</p>",
     ["Can you articulate why you have hope in Christ?", "How do gentleness and respect shape apologetics?", "What questions about your hope have you received?"]),
    (258, 60, 4, 8,
     "Above all, love each other deeply, because love covers over a multitude of sins.",
     "<p>Peter prepares churches for fiery trial and eschatological nearness. Deep mutual love forgives and shields community from fracture when sin and pressure abound.</p>",
     "<p>After urging prayer, hospitality, and stewarding gifts, Peter commands fervent love among believers because love covers many sins — prioritizing reconciliation over exposure.</p>",
     ["How does deep love cover sin without ignoring justice?", "Who needs your fervent love in a hard season?", "What sin fracture could love help heal?"]),
    (259, 60, 5, 7,
     "Cast all your anxiety on him because he cares for you.",
     "<p>Peter closes with humility under God's mighty hand and resistance to the devil. Anxiety is not to be carried alone but hurled onto a caring Father who sustains his flock.</p>",
     "<p>After exhorting elders and younger members, Peter calls humility and vigilance against the devil. Cast all anxiety on God because he cares for you.</p>",
     ["What anxieties are you still carrying alone?", "How does knowing God cares change your worry?", "What practice helps you cast cares on him daily?"]),
    (260, 61, 1, 3,
     "His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.",
     "<p>2 Peter combats false teachers and moral laxity. Divine power through knowing Christ supplies full resources for godliness — no supplemental secret knowledge required.</p>",
     "<p>Peter opens with grace and peace through knowledge of God and Jesus. His divine power granted all needed for life and godliness through knowing the one who called by glory and virtue.</p>",
     ["What do you feel is missing for godly living that God has actually provided?", "How does knowing Christ supply power?", "What false teachers promise what only Christ gives?"]),
    (261, 61, 3, 9,
     "The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance.",
     "<p>Scoffers mock delay of Christ's return; Peter reframes time from God's patience toward repentance, not indifference. God's slowness is mercy for salvation.</p>",
     "<p>Peter reminds readers of creation, flood, and future judgment by fire. The Lord's apparent delay is patience, desiring none to perish but all to repent.</p>",
     ["Where are you impatient with God's timing?", "How does divine patience motivate evangelism?", "Who might still repent because God waits?"]),
    (262, 61, 3, 18,
     "But grow in the grace and knowledge of our Lord and Savior Jesus Christ. To him be glory both now and forever! Amen.",
     "<p>2 Peter closes urging stability amid deception. Growth is not self-generated achievement but increasing grace and knowledge of Jesus, culminating in doxology.</p>",
     "<p>After warning about lawless teachers and unstable twisting of Paul's letters, Peter commands growth in grace and knowledge of Jesus, giving him eternal glory.</p>",
     ["How are you growing in grace and knowledge this year?", "What instability pulls you from steady growth?", "How does doxology cap Christian instruction?"]),
    (263, 62, 1, 9,
     "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.",
     "<p>1 John addresses fellowship with God and one another. Confession is not groveling but agreement with God about sin, triggering faithful, just forgiveness and cleansing.</p>",
     "<p>John proclaims fellowship with Father and Son, walking in light. If we confess sins, God is faithful and just to forgive and cleanse from all unrighteousness.</p>",
     ["What sin do you need to confess to restore fellowship?", "How are faithfulness and justice part of forgiveness?", "Why is purification more than mere pardon?"]),
    (264, 62, 4, 8,
     "Whoever does not love does not know God, because God is love.",
     "<p>1 John 4 centers divine love revealed at the cross. Lack of love proves lack of knowing God whose essential nature is love — not mere attribute but being.</p>",
     "<p>John warns against false spirits and proclaims God's love sent in the Son as propitiation. Whoever does not love does not know God, for God is love.</p>",
     ["How does knowing God as love change how you love enemies?", "Where is lovelessness revealing gaps in knowing God?", "How was love defined at the cross?"]),
    (265, 62, 4, 10,
     "This is love: not that we loved God, but that he loved us and sent his Son as an atoning sacrifice for our sins.",
     "<p>John reverses human-centered love stories. True love originates in God's initiative — sending the Son as atoning sacrifice while humanity was still indifferent or hostile.</p>",
     "<p>After stating God is love, John defines it: not our love for God first, but his love sending the Son as propitiation for our sins — initiating reconciliation.</p>",
     ["How does God's first love free you from performance?", "What does atoning sacrifice mean for your guilt?", "How can you reflect initiatory love toward others?"]),
    (266, 63, 1, 5,
     "And now, dear lady, I am not writing you a new command but one we have had from the beginning. I ask that we love one another.",
     "<p>2 John is a brief letter to a church ('elect lady') threatened by deceivers denying Christ's coming in flesh. Love one another is ancient command, not novelty.</p>",
     "<p>John rejoices that children walk in truth. He repeats the command from the beginning: love one another — truth and love inseparable against false teachers.</p>",
     ["How does love protect truth in your community?", "Why does John stress this is not a new command?", "Who in your church family needs steadfast love?"]),
    (267, 64, 1, 7,
     "It was for the sake of the Name that they went out, receiving no help from the pagans.",
     "<p>3 John commends Gaius for supporting traveling missionaries who depend on churches, not Gentile hospitality, because they go out for the Name of Christ.</p>",
     "<p>John praises Gaius's faithfulness to truth and hospitality to brothers strangers to him. They went out for the Name's sake, taking nothing from pagans.</p>",
     ["How can you support gospel workers today?", "What does going out 'for the Name' mean?", "Why is church partnership vital for mission?"]),
    (268, 65, 1, 24,
     "To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy—",
     "<p>Jude warns against infiltrating false teachers and urges contending for faith once delivered. The doxology trusts God's power to preserve believers blameless for joyful presentation.</p>",
     "<p>After examples of judgment and exhortation to build yourselves up in prayer, Jude blesses God able to keep from stumbling and present blameless with joy before his glory.</p>",
     ["What makes you fear stumbling before God?", "How does God's keeping power encourage perseverance?", "What joy awaits blameless presentation in glory?"]),
    (269, 66, 1, 3,
     "Blessed is the one who reads aloud the words of this prophecy, and blessed are those who hear it and take to heart what is written in it, because the time is near.",
     "<p>Revelation is apocalyptic letter to seven Asian churches under imperial cult pressure. Blessing attends public reading, hearing, and obeying prophecy because eschatological fulfillment is imminent.</p>",
     "<p>John's prologue echoes Daniel and prophets: blessed is reader, hearers, and those who keep what is written, for the time is near — calling active obedience.</p>",
     ["How do you 'take to heart' apocalyptic Scripture?", "Why might public reading have mattered to persecuted churches?", "What does 'the time is near' mean for obedience now?"]),
    (270, 66, 2, 10,
     "Do not be afraid of what you are about to suffer. I, the one who holds the keys of death and Hades, tell you, the devil will put some of you in prison to test you, and you will suffer persecution for ten days. Be faithful, even to the point of death, and I will give you life as your victor's crown.",
     "<p>Christ's letter to Smyrna addresses a poor yet rich church facing synagogue slander and impending Roman persecution. The risen Lord holds death's keys and promises crown for faithful endurance.</p>",
     "<p>Jesus knows their tribulation and poverty yet spiritual wealth. He commands fearlessness before coming suffering, satanic imprisonment, and calls faithfulness unto death for victor's crown of life.</p>",
     ["What suffering makes you afraid today?", "How does Christ holding death's keys change fear?", "What does faithful endurance look like under pressure?"]),
    (271, 66, 3, 20,
     "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.",
     "<p>Christ's letter to lukewarm Laodicea rebukes self-sufficient wealth. The knocking Christ seeks intimate table fellowship — a shocking image of Messiah requesting entry to his church.</p>",
     "<p>After rebuking nauseating lukewarmness and advising gold, white garments, and eye salve, Jesus stands at the door knocking, promising shared meal with whoever opens.</p>",
     ["Where might Christ be knocking at a closed door in your life?", "What does shared meal signify about fellowship with Jesus?", "How does lukewarmness block hearing his voice?"]),
    (272, 66, 4, 8,
     "Each of the four living creatures had six wings and was covered with eyes all around, even under its wings. Day and night they never stop saying: \"Holy, holy, holy is the Lord God Almighty,\" who was, and is, and is to come.",
     "<p>John is caught up through an open door to heaven's throne room. Living creatures echo Isaiah 6 and Ezekiel 1 in ceaseless Trisagion worship of the eternal Almighty.</p>",
     "<p>After describing throne, emerald rainbow, and twenty-four elders, John sees four creatures full of eyes proclaiming day and night: Holy, holy, holy — Lord God Almighty, who was, is, and is to come.</p>",
     ["How does eternal worship reshape your view of history?", "What does God's holiness mean in a casual culture?", "How can your worship join heaven's ceaseless praise?"]),
    (273, 66, 5, 5,
     "Then one of the elders said to me, \"Do not weep! See, the Lion of the tribe of Judah, the Root of David, has triumphed. He is able to open the scroll and its seven seals.\"",
     "<p>No one in heaven or earth can open the scroll of destiny until the Lion-Lamb appears. Judah's lion and David's root conquers through slaughtered worthiness, not mere military might.</p>",
     "<p>John weeps because no one is worthy to open the scroll. An elder points to the Lion of Judah, Root of David, who has conquered and can open the scroll and seals.</p>",
     ["What makes you weep when history seems locked?", "How does Christ's triumph differ from worldly conquest?", "Why is the Lamb's worthiness central to God's plan?"]),
    (274, 66, 7, 9,
     "After this I looked, and there before me was a great multitude that no one could count, from every nation, tribe, people and language, standing before the throne and before the Lamb. They were wearing white robes and were holding palm branches in their hands.",
     "<p>Between seal judgments John sees cosmic worship and the sealed 144,000, then an innumerable international multitude — gospel hope that every people group stands before the Lamb.</p>",
     "<p>After the sixth seal's terror, an elder explains the great multitude from all nations in white robes with palm branches before throne and Lamb — victors from great tribulation.</p>",
     ["How does Revelation's diversity challenge your view of heaven?", "Who from another nation or language expands your worship vision?", "What does white robes and palm branches signify?"]),
    (275, 66, 12, 11,
     "They triumphed over him by the blood of the Lamb and by the word of their testimony; they did not love their lives so much as to shrink from death.",
     "<p>Chapter 12 portrays cosmic war: dragon versus woman and child. Believers overcome Satan not by political power but Lamb's blood, truthful witness, and willingness to die.</p>",
     "<p>Michael expels the accuser; heaven rejoices. Brothers and sisters conquer the devil by the Lamb's blood, their testimony word, and not loving lives unto death-avoidance.</p>",
     ["How does the Lamb's blood enable victory over accusation?", "What is the word of your testimony?", "What would not loving your life look like in witness?"]),
    (276, 66, 19, 11,
     "I saw heaven standing open and there before me was a white horse, whose rider is called Faithful and True. With justice he judges and wages war.",
     "<p>Revelation 19 celebrates marriage supper of the Lamb then portrays parousia as divine warrior-judge on white horse — faithful, true, righteous warfare against evil.</p>",
     "<p>After heaven's Hallelujah and the Lamb's wedding, heaven opens revealing a white horse whose rider Faithful and True judges and makes war in righteousness.</p>",
     ["How do faithfulness and truth characterize Christ's return?", "Why does justice require judgment as well as mercy?", "How should this vision affect hope and holiness?"]),
    (277, 66, 21, 5,
     "He who was seated on the throne said, \"I am making everything new!\" Then he said, \"Write this down, for these words are trustworthy and true.\"",
     "<p>New Jerusalem descends as bride; death, mourning, and pain pass away. The one on the throne announces universal renewal — creation's final healing in Christ.</p>",
     "<p>After God dwells with humanity and wipes every tear, the enthroned one declares making all things new, commanding John to write because these words are faithful and true.</p>",
     ["What broken thing do you long for God to make new?", "How does creation renewal differ from escape from earth?", "Why must these words be written and trusted?"]),
    (278, 66, 22, 12,
     "Look, I am coming soon! My reward is with me, and I will give to each person according to what they have done.",
     "<p>Revelation closes with epilogue affirming prophecy's authority. Jesus repeats imminent coming, bringing recompense aligned with deeds — grace and accountability united.</p>",
     "<p>After river of life and invitation to take water of life freely, Jesus declares he is coming soon with reward, rendering to each according to deeds, affirming Alpha and Omega identity.</p>",
     ["How does 'coming soon' shape urgency in discipleship?", "How do grace and deeds fit together at Christ's return?", "What reward are you storing through faithfulness?"]),
]

ALL = LESSONS + LESSONS_2 + LESSONS_3


def main() -> None:
    assert len(ALL) == 113, f"expected 113 lessons, got {len(ALL)}"
    lessons = []
    for row in ALL:
        lesson, book_id, chapter, verse, text, hist, narr, questions = row
        lessons.append({
            "lesson": lesson,
            "book_id": book_id,
            "chapter": chapter,
            "verse_start": verse,
            "verse_end": verse,
            "text": text,
            "historical_context": hist,
            "preceding_narrative": narr,
            "discussion_questions": questions,
        })
    lessons.sort(key=lambda x: x["lesson"])
    assert lessons[0]["lesson"] == 166
    assert lessons[-1]["lesson"] == 278
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(lessons, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(lessons)} lessons to {OUT}")


if __name__ == "__main__":
    main()
